### ISSUE TITLE
applications not installing from ts wizard

### ISSUE THREAD

**Issue by Audigy35** [FriendsOfMDT/PSD#74]
when selecting single application  or multiple applications from the deployment wizard they are ignored.
[PSDApplications.log](https://github.com/FriendsOfMDT/PSD/files/11010488/PSDApplications.log)
[smsts.log](https://github.com/FriendsOfMDT/PSD/files/11010489/smsts.log)

**Comment by GeoSimos** [comment]
Hi @Audigy35,

The 1st thing you need to be aware of, is that application bundles is not implemented yet.

Could you also include the following from you Deployment Share\Control folder:
1) Your task sequence ts.xml file which is under the folder with the ID you provided when created the TS.
2) The applications.xml file from the control folder. 
Thank you

**Comment by Audigy35** [comment]
Here are the files you requested.

**Comment by Audigy35** [comment]
[Applications.txt](https://github.com/FriendsOfMDT/PSD/files/11014283/Applications.txt)
[ts.txt](https://github.com/FriendsOfMDT/PSD/files/11014288/ts.txt)

**Comment by Audigy35** [comment]
you that that application bundles is not implemented yet,what about sql database connectivity and usmt?

**Comment by Audigy35** [comment]
Installing the application only works if I add a step to the task sequence to install single application but not from wizard,as for you questions it’s a new deploymentshare and files do exist in the application folder.

**Comment by GeoSimos** [comment]
Hi @Audigy35,

I have some news for you but first let me tell you that by adding each application as a step in a Task Sequence is functional (that is what I was referring to).
Now onto the Wizard issue, I was able to reproduce the problem, I have two applications in one of my deployment shares, when I use any task sequence, I see only one (the first I created). 
However if I go to the "Search" box and type the asterisk (*) wildcard character, all the applications are listed and I can multi-select by holding down CTRL and click on the entries I need to install.
For this to work, the default "Install Applications" step is needed, also this is needed for the Mandatory applications, those you can set them in the CustomSettings.ini file per the official documentation reference here [MandatoryApplications](https://learn.microsoft.com/en-us/mem/configmgr/mdt/toolkit-reference#MandatoryApplications).
I will report the issue to the team today in our meeting. When a fix is ready I will update this issue item.

**Comment by PowerShellCrack** [comment]
At first, I thought that this may be an issue with the new PSDWizard, so I re-tested this. I setup a basic PSD Tasksequence and ensured the _Install Application_ step was in the task sequence and set to _Install multiple applications_ 

**REQUIRED**: Like in regular MDT and what @GeoSimos has mentioned, this step is required if you want apps to install from either the selection screen in wizard and/or from mandatory apps set in _customsettings.ini_. If none of these exist this step will be skipped. 

![image](https://user-images.githubusercontent.com/20599825/227724824-e83e9521-27ed-41b6-b8e9-3281e239ad4d.png)
(I did disable the Windows update steps to speed things up....)

For further clarity, I have **no** mandatory applications in my _customsettings.ini_, but I do have SkipApplications=NO set
![image](https://user-images.githubusercontent.com/20599825/227726069-0725c361-d3b3-4916-ad6d-1f3ce37e38c7.png)

When the wizard came up, I selected some apps. 

![image](https://user-images.githubusercontent.com/20599825/227724958-6b401ee2-249f-4dee-b70c-5e457e63985c.png)

If _SkipSummary_ is **not** set to YES (or not configured), you will also get a summary screen with the selected items from the UI including the list of selected applications.

![image](https://user-images.githubusercontent.com/20599825/227725411-eaa5e3ff-4cce-4d38-91c1-11beffc6e2cc.png)

Another way to check if UI exported the list to _Applications_ variable is to check the _PSDStart.log_ under _<OSDrive>\MININT\SMSOSD\OSDLOGS\_

Look for _Export-PSDWizardResult: Property Applications is now:_ (the applications will be translated into their GUID from Applications.xml)

Ultimately that will add the apps to the **active** tsenv variables like this: 
![image](https://user-images.githubusercontent.com/20599825/227774867-04b8a95e-345f-4dd2-9b44-b748d800b2f3.png)

![image](https://user-images.githubusercontent.com/20599825/227725776-98a5e51e-1d4d-455c-ab8a-015cbbd91141.png)

During the post deployment the applications install step will come up...
![image](https://user-images.githubusercontent.com/20599825/227774247-94fea726-87ea-437a-bf79-ec7f9c33c489.png)
(my applications are using a WSF script; that is why the command window comes up)

Both apps are installed 
![image](https://user-images.githubusercontent.com/20599825/227816414-cdea0de4-f513-4899-a802-94e10c6d53d2.png)

**You're not seeing this? Can you confirm these steps?**

TIPS:
- When running PSD over the internet or cloud, if the application **directory** has certain special characters in it, like mine did for the **++** in path _\\Applications\\INSTALL \- Notepad++_, webdav's directory discovery may fail as did mine in the past.

- During my testing, one of my apps wasn't installing because it was missing a file the wsf was calling and it looked as though it just skipped right past the install. Just make sure the application will install from command line. 

Sorry about all the screenshot, but I figured I'd want to get full clarity and what you can do to troubleshoot the issue.

**Comment by Audigy35** [comment]
install applications from the wizard works after adding skipApplications to custom.ini

**Comment by PowerShellCrack** [comment]
oh, that is interesting, You added _SkipApplications=NO_ and it showed in the UI? or it somehow triggered the Application install?

**Comment by GeoSimos** [comment]
> * When running PSD over the internet or cloud, if the application **directory** has certain special characters in it, like mine did for the **++** in path _\Applications\INSTALL - Notepad++_, webdav's directory discovery may fail as did mine in the past.
> * During my testing, one of my apps wasn't installing because it was missing a file the wsf was calling and it looked as though it just skipped right past the install. Just make sure the application will install from command line.
> 
Thanks for answering in that issue Rick (I was going to update you about it issue via email to make you aware).
Regarding the double plus signs, the problem (which is not a problem but a security feature) lies in the configuration of IIS which considers them as double escape sequence characters and blocks them.
We fixed this issue in a couple of previous submits here by enabling the allowance of double escape characters when setting ups the Web server. However, if someone has setup their IIS way back before this change, they can go to IIS and enable it on the website or any virtual directory underneath that serves as a Deployment Share.
Here are some shots for better understanding:
 
![image](https://user-images.githubusercontent.com/22078536/228064443-5562822d-4c7c-44d3-8021-eae7517f0e97.png)
![image](https://user-images.githubusercontent.com/22078536/228064493-188b49a9-bce8-416a-9608-6aa5a31615e5.png)

**Comment by PowerShellCrack** [comment]
Thanks for the feedback on IIS. I just changed the directory path with supported characters. I will change the IIS settings later on. 

For the application install issue, I did test a deployment with the _SkipApplications_ removed entirely from _customsettings.ini_ and the application page still showed in UI as expected. All **unhidden** and **enabled** applications in the list should show up by default. The search will filter the list that _contains_ the characters in the name. 

**I did find a bug though.**: If you do a search, then click clear; it supposed to bring back the list which it does not. But you can still search for the apps. A workaround is, if you use * in the search it will show all available apps. I will add this to my bug list. 

However, this doesn't affect the multiple app installs as long as you are able to select multiple apps in this screen.

**Comment by GeoSimos** [comment]
**With disabled property of _SkipApplications_ or set as _SkipApplications=NO_** 

OK I found the culprit of the non-displaying Application @PowerShellCrack, for an unknown reason (probably an MTD GUI's quirk), the MSI application of Foxit Reader didn't had a value in the "Hidden" column, however the checkbox that hides the app wasn't checked in the properties of it.
I checked it and it switched to "True" in the GUI, unchecked it and switched to "False", restarted the boot to the TS and all the apps are displaying fine in the Wizard, maybe though a suggestion would be to check both "False" and NULL values of the hidden application flag.
The other application I have "Notepad++" had the hidden flag as "False", that's the reason it was displaying.

**Comment by GeoSimos** [comment]
I guess we can close this issue right @Audigy35?

**Comment by PowerShellCrack** [comment]
> **With disabled property of _SkipApplications_ or set as _SkipApplications=NO_**
> 
> OK I found the culprit of the non-displaying Application @PowerShellCrack, for an unknown reason (probably an MTD GUI's quirk), the MSI application of Foxit Reader didn't had a value in the "Hidden" column, however the checkbox that hides the app wasn't checked in the properties of it. I checked it and it switched to "True" in the GUI, unchecked it and switched to "False", restarted the boot to the TS and all the apps are displaying fine in the Wizard, maybe though a suggestion would be to check both "False" and NULL values of the hidden application flag. The other application I have "Notepad++" had the hidden flag as "False", that's the reason it was displaying.

Nice find! I will also add that to the list to check for null values as well.

**Comment by Audigy35** [comment]
yes indeed thakyou very mouch

**Comment by GeoSimos** [comment]
You're welcome @Audigy35, thank you for raising this, it helps us locate more issues and fix or provide workarounds.
